# Don't print a new line at the start of the prompt
add_newline = false
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
symbol = "➜"     # The "symbol" segment is being set to "➜"
error_symbol = "✗"
use_symbol_for_status = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[directory]
truncation_length = 8

[username]
disabled = false
show_always = true

prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "docker_context",
    "package",
    "dotnet",
    "elixir",
    "elm",
    "erlang",
    "golang",
    "java",
    "julia",
    "nim",
    "nodejs",
    "ocaml",
    "php",
    "purescript",
    "python",
    "ruby",
    "rust",
    "terraform",
    "zig",
    "nix_shell",
    "conda",
    "memory_usage",
    "aws",
    "env_var",
    "crystal",
    "cmd_duration",
    "custom",
    "line_break",
    "jobs",
    "battery",
    "time",
    "character",
]


[jobs]
symbol = "+ "
threshold = 4

[memory_usage]
disabled = true
show_percentage = true
show_swap = false
threshold = -1

[docker_context]
disabled = false

[kubernetes]
disabled = false 