# Don't print a new line at the start of the prompt
add_newline = false
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold green) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[directory]
truncation_length = 8

[username]
style_user = "yellow bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[kubernetes]
format = '[☸ $context $namespace](dimmed blue) '
disabled = false

[jobs]
symbol = "+ "
threshold = 4

[memory_usage]
disabled = true
show_percentage = true
show_swap = false
threshold = -1

[docker_context]
disabled = false
