#!/bin/zsh
#ZSH Autoload
autoload -Uz compinit promptinit
compinit
promptinit

# all of our zsh files
typeset -U config_files
config_files=(~/.zsh/*.zsh)

# load the path files
for file in ${config_files}; do
  source "$file"
done

eval "$(starship init zsh)"

# load antibody plugins
source <(antibody init)
antibody bundle < ~/.zsh_plugins.txt 

setopt inc_append_history share_history autocd autopushd pushdignoredups 
setopt COMPLETE_ALIASES

zstyle ':completion::complete:*' gain-privileges 1

# History
SAVEHIST=10000
HISTFILE=~/.zsh_history


bindkey '^[l' autosuggest-accept
bindkey '^[^M' autosuggest-execute