#!/bin/zsh
#ZSH Autoload
autoload -Uz compinit promptinit
compinit
promptinit

export STARSHIP_CONFIG=~/.zsh/starship.toml
export SPACESHIP_USER_SHOW="always"
export SPACESHIP_HOST_SHOW="always"
eval "$(starship init zsh)"


# Plugin Section
# configure zsh-autosuggestions
export FZF_DEFAULT_COMMAND="fd --one-file-system --type f --hidden . $HOME"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --one-file-system --type d --hidden --exclude .git . $HOME"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=242,bg=grey,bold,underline"
export ZSH_AUTOSUGGEST_STRATEGY=(history completion) 
export AUTO_NOTIFY_EXPIRE_TIME=300000

# all of our zsh files
typeset -U config_files
config_files=(~/.zsh/*.zsh)

# load the path files
for file in ${config_files}; do
  source "$file"
done

# load antibody plugins
source <(antibody init)
antibody bundle < ~/.zsh_plugins.txt 

# Krew Kubectl Plugin Manager
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"


setopt inc_append_history share_history autocd autopushd pushdignoredups 
setopt COMPLETE_ALIASES

zstyle ':completion::complete:*' gain-privileges 1

# History
SAVEHIST=10000
HISTFILE=~/.zsh_history


bindkey '^[l' autosuggest-accept
bindkey '^[^M' autosuggest-execute