#!/bin/zsh
#ZSH Autoload
autoload -Uz compinit promptinit
compinit
promptinit

eval "$(starship init zsh)"

# load antibody plugins
source <(antibody init)
antibody bundle < ~/.zsh_plugins.txt 

# all of our zsh files
typeset -U config_files
config_files=(~/.zsh/*.zsh)

# load the path files
for file in ${config_files}; do
  source "$file"
done

# define PATH
export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/local/go/bin:$HOME/bin:$HOME/.krew/bin:$HOME/.cargo/bin"

# load zsh completion files
fpath=(~/.zsh/completions $fpath) 
autoload -U compinit && compinit

setopt inc_append_history share_history autocd autopushd pushdignoredups 
setopt COMPLETE_ALIASES

zstyle ':completion::complete:*' gain-privileges 1

# History
SAVEHIST=100000
HISTFILE=~/.zsh_history

umask 022

#Start tmux

if [ -z "$TMUX" ]
then
    tmux attach -t TMUX || tmux new -s TMUX
fi

